MPI_INF_3DHP_JOINTS = [
    'spine_3',
    'spine_4',
    'spine_2',
    'Spine (H36M)',  # close to spine2
    'pelvis',
    'neck',  # throat
    'head',
    'headtop',
    'left_clavicle',
    'left_shoulder',
    'left_elbow',
    'left_wrist',
    'left_hand',
    'right_clavicle',
    'right_shoulder',
    'right_elbow',
    'right_wrist',
    'right_hand',
    'left_hip',
    'left_knee',
    'left_ankle',
    'left_foot',
    'left_toe',
    'right_hip',
    'right_knee',
    'right_ankle',
    'right_foot',
    'right_toe'
]
